Add skip_default_scalars option
graphql-rust/graphql-client pull request #437
Opened 2022-09-21 11:29 UTC by fenhl

Closes #432.

2022-09-23 08:26 UTC, tomhoule reviewed
That looks good to me. It is only missing tests. Would you be prepared to write one? I think we would want to test that including that option, providing custom types for some of the default scalars and deserializing a specific JSON file, we have the values we expect.

2023-10-12 23:47 UTC, mathstuf requested changes
Looks good to me; just needs tests.

2025-01-31 07:18 UTC, tomhoule commented
This PR is quite old, I'm going to close it, but anybody feel free to reopen if there is interest in this feature, and pushing this to the finish line.

2025-01-31 07:18 UTC, closed without merging

2025-01-31 14:03 UTC, mathstuf commented
Can we get a label for "closed for staleness reasons" so that they can be resurrected more easily?

2025-01-31 18:50 UTC, tomhoule commented
Done :)