support `extend type Foo`
graphql-rust/graphql-client pull request #447
Opened 2023-04-01 11:20 UTC by pizzacat83

Fixes #353

2023-04-26 23:27 UTC, pizzacat83 commented
I apologize for opening PRs with failing checks.

The [lint check](https://github.com/graphql-rust/graphql-client/actions/runs/4737659574/jobs/8532153743?pr=447) seems to be failing due to code unrelated to this PR. Should I change that code in this PR?

2023-04-27 09:06 UTC, tomhoule commented
No worries! I'm not working actively on this project, but hopefully someone can do a proper review. Don't worry about clippy if it's unrelated.

2023-10-12 23:46 UTC, mathstuf commented
FWIW, the clippy things are fixed in #449.

2023-10-23 10:14 UTC, mathstuf requested changes

2023-10-23 10:14 UTC, mathstuf commented on graphql_client_codegen/src/deprecation.rs
>      Deny,
This doesn't preserve the previous value. I think these clippy fixes belong in its own PR to avoid any confusion about what this PR is about.

2023-10-23 10:14 UTC, mathstuf commented on graphql_client_codegen/src/tests/foobars_query.graphql
> +  fooBars {
This reindentation is just noise here.

2023-10-25 10:19 UTC, pizzacat83 commented
Apologies for the noisy commits. I've reverted those changes, so now this PR contains only the relevant diffs.

2023-10-28 14:49 UTC, mathstuf commented
Thanks. I've rebased those commits out so that they're not added-and-removed in the same PR. Could you do the same or allow maintainers to push to the branch?

2023-10-28 14:50 UTC, mathstuf commented
Oh, it did allow me to do so; the error I saw was about not having permission to push tags.

2023-10-28 14:53 UTC, mathstuf approved these changes
I've rebased out the manual fixes and squashed commits together so that it all passes CI in one shot.

2023-10-28 15:40 UTC, merged